version: '3'

services:
  postgres:
    image: 'postgres:14.2-alpine'
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password